/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Explore` | `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/addingbusines/addshop`; params?: Router.UnknownInputParams; } | { pathname: `/MyBusines/Mybssuinesss`; params?: Router.UnknownInputParams; } | { pathname: `/businesmainscareen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownInputParams & { category: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Explore` | `/Explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/addingbusines/addshop`; params?: Router.UnknownOutputParams; } | { pathname: `/MyBusines/Mybssuinesss`; params?: Router.UnknownOutputParams; } | { pathname: `/businesmainscareen/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownOutputParams & { category: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Explore${`?${string}` | `#${string}` | ''}` | `/Explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/addingbusines/addshop${`?${string}` | `#${string}` | ''}` | `/MyBusines/Mybssuinesss${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Explore` | `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/addingbusines/addshop`; params?: Router.UnknownInputParams; } | { pathname: `/MyBusines/Mybssuinesss`; params?: Router.UnknownInputParams; } | `/businesmainscareen/${Router.SingleRoutePart<T>}` | `/businesslist/${Router.SingleRoutePart<T>}` | { pathname: `/businesmainscareen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownInputParams & { category: string | number; } };
    }
  }
}
